package de.baleipzig.products;

import de.baleipzig.products.persistance.Product;
import de.baleipzig.products.persistance.ProductNotFoundException;
import de.baleipzig.products.persistance.ProductRepository;
import org.springframework.data.jpa.domain.AbstractPersistable;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;


@RestController
public class ProductController {

    private final ProductRepository repository;

    public ProductController(ProductRepository repository) {
        this.repository = repository;
    }

    @GetMapping("/products")
    public List<Long> all(){

        List<Product> products = repository.findAll();
        return products.stream()
                .map(AbstractPersistable::getId)
                .toList();
    }

    @PostMapping(value = "/products", consumes = "application/json")
    public Long newProduct(@RequestBody @Valid ProductDTO dtoProduct) {


        Product product = repository.save(new Product(dtoProduct));

        // return autogenerated id in response
        return product.getId();
    }

    @GetMapping("/products/{id}")
    public ProductDTO one(@PathVariable long id){
        return repository.findById(id)
                .map(this::convertToDto)
                .orElseThrow(() -> new ProductNotFoundException(id));
    }

    /**
     * Updated ein Produkt.
     * @param dtoProduct Die neuen Daten für das Produkt
     * @param id die ID des Produktes, das bearbeitet werden soll
     * @return die ID des Updateten Produkt
     */
    @PutMapping(value = "/products/{id}", consumes = "application/json", produces = "application/json")
    public long replaceProduct(@RequestBody @Valid ProductDTO dtoProduct, @PathVariable Long id) {

        Product newProduct = new Product(dtoProduct);

        return repository.findById(id)
                .map(product -> {
                    product.setName(newProduct.getName());
                    product.setProductType(newProduct.getProductType());
                    product.setProperty(newProduct.getProperty());
                    Product savedProduct = repository.save(product);
                    return savedProduct.getId();
                })
                .orElseThrow(() -> new ProductNotFoundException(id));
    }


    @DeleteMapping("/products/{id}")
    public void deleteProduct(@PathVariable Long id) {

        if (repository.findById(id).isEmpty()) {
            throw new ProductNotFoundException(id);
        }
        repository.deleteById(id);
    }


    private ProductDTO convertToDto (Product product) {

        return new ProductDTO(
                product.getProductType(),
                product.getName(),
                product.getProperty());
    }
}
