package de.baleipzig.products;

import de.baleipzig.products.persistance.Product;
import de.baleipzig.products.persistance.ProductNotFoundException;
import de.baleipzig.products.persistance.ProductRepository;
import org.springframework.data.jpa.domain.AbstractPersistable;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class ProductService {

    private final ProductRepository repository;
    private final MapperFactory mapperFactory;

    public ProductService(ProductRepository repository, MapperFactory mapperFactory) {
        this.repository = repository;
        this.mapperFactory = mapperFactory;
    }

    public List<Long> getAllProducts() {
        List<Product> products = repository.findAll();
        return products.stream()
                .map(AbstractPersistable::getId)
                .toList();
    }

    public Long saveProduct(ProductDTO dtoProduct) {
        Product product = repository.save(mapperFactory.mapProduct(dtoProduct));

        // return autogenerated id in response
        return product.getId();
    }

    public ProductDTO getOneProduct(Long id) throws ProductNotFoundException {
        return repository.findById(id)
                .map(this::convertToDto)
                .orElseThrow(() -> new ProductNotFoundException(id));
    }

    public Long updateProduct(ProductDTO dtoProduct, Long id) throws ProductNotFoundException {
        Product newProduct = mapperFactory.mapProduct(dtoProduct);

        return repository.findById(id)
                .map(product -> {
                    product.setName(newProduct.getName());
                    product.setProductType(newProduct.getProductType());
                    product.setProperty(newProduct.getProperty());
                    Product savedProduct = repository.save(product);
                    return savedProduct.getId();
                })
                .orElseThrow(() -> new ProductNotFoundException(id));
    }

    public void deleteProduct(Long id){
        if (repository.findById(id).isEmpty()) {
            throw new ProductNotFoundException(id);
        }
        repository.deleteById(id);
    }

    private ProductDTO convertToDto (Product product) {

        return new ProductDTO(
                product.getProductType().name(),
                product.getName(),
                product.getProperty());
    }
}
