package de.baleipzig.products;

import de.baleipzig.products.persistance.Product;
import de.baleipzig.products.persistance.ProductNotFoundException;
import de.baleipzig.products.persistance.ProductRepository;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;


@RestController
public class ProductController {

    private final ProductRepository repository;

    public ProductController(ProductRepository repository) {
        this.repository = repository;
    }

    @GetMapping("/products")
    public List<Product> all(){
        return repository.findAll();
    }

    @PostMapping(value = "/products", consumes = "application/json")
    public ResponseEntity<Object> newProduct(@RequestBody ProductDTO dtoProduct) {
        Product newProduct = new Product(dtoProduct);

        Product product = repository.save(newProduct);

        // return autogenerated id in response
        return new ResponseEntity<>(String.valueOf(product.getId()), HttpStatus.OK);
    }

    @GetMapping("/products/{id}")
    public Product one(@PathVariable long id){
        return repository.findById(id)
                .orElseThrow(() -> new ProductNotFoundException(id));
    }

    /**
     * Updated ein Produkt.
     * @param dtoProduct Die neuen Daten für das Produkt
     * @param id die ID des Produktes, das bearbeitet werden soll
     * @return die ID des Updateten Produkt
     */
    @PutMapping(value = "/products/{id}", consumes = "application/json", produces = "application/json")
    public ResponseEntity<String> replaceProduct(@RequestBody ProductDTO dtoProduct, @PathVariable Long id) {

        Product newProduct = new Product(dtoProduct);

        return repository.findById(id)
                .map(product -> {
                    product.setName(newProduct.getName());
                    product.setProductType(newProduct.getProductType());
                    product.setEigenschaft(newProduct.getEigenschaft());
                    Product savedProduct = repository.save(product);
                    return new ResponseEntity<>(String.valueOf(savedProduct.getId()), HttpStatus.OK);
                })
                .orElseGet(() -> {
                    Product savedProduct = repository.save(newProduct);
                    return new ResponseEntity<>(String.valueOf(savedProduct.getId()), HttpStatus.OK);
                });
    }


    @DeleteMapping("/products/{id}")
    public void deleteProduct(@PathVariable Long id) {
        repository.deleteById(id);
    }

}
